// Auto-generated by ntapi-helper. Source: phnt (phnt_ntdef.h)
// Include <windows.h> beforehand for primitives (NTSTATUS, HANDLE, ULONG, ...).

#include <Windows.h>

#ifndef NT_SUCCESS
#define NT_SUCCESS(Status) (((NTSTATUS)(Status)) >= 0)
#endif
#ifndef OBJ_CASE_INSENSITIVE
#define OBJ_CASE_INSENSITIVE 0x00000040L
#endif
#ifndef InitializeObjectAttributes
#define InitializeObjectAttributes(p, n, a, r, s) { \
    (p)->Length = sizeof(OBJECT_ATTRIBUTES); \
    (p)->RootDirectory = (r); \
    (p)->Attributes = (a); \
    (p)->ObjectName = (n); \
    (p)->SecurityDescriptor = (s); \
    (p)->SecurityQualityOfService = NULL; \
}
#endif

#ifndef STATUS_SUCCESS
#define STATUS_SUCCESS              ((NTSTATUS)0x00000000L)
#endif
#ifndef STATUS_UNSUCCESSFUL
#define STATUS_UNSUCCESSFUL         ((NTSTATUS)0xC0000001L)
#endif
#ifndef STATUS_PROCEDURE_NOT_FOUND
#define STATUS_PROCEDURE_NOT_FOUND  ((NTSTATUS)0xC000007AL)
#endif
#ifndef STATUS_INVALID_IMAGE_FORMAT
#define STATUS_INVALID_IMAGE_FORMAT ((NTSTATUS)0xC000007BL)
#endif

typedef enum _SECTION_INHERIT
{
    ViewShare = 1, // The mapped view of the section will be mapped into any child processes created by the process.
    ViewUnmap = 2 // The mapped view of the section will not be mapped into any child processes created by the process.
} SECTION_INHERIT;

// --- typedef UNICODE_STRING  (phnt_ntdef.h, source: phnt)
typedef struct _UNICODE_STRING
{
    USHORT Length;
    USHORT MaximumLength;
    PWCH Buffer;
} UNICODE_STRING, * PUNICODE_STRING;

// --- typedef PCUNICODE_STRING  (phnt_ntdef.h, source: phnt)
typedef const UNICODE_STRING* PCUNICODE_STRING;

// --- typedef OBJECT_ATTRIBUTES  (phnt_ntdef.h, source: phnt)
typedef struct _OBJECT_ATTRIBUTES
{
    ULONG Length;
    HANDLE RootDirectory;
    PCUNICODE_STRING ObjectName;
    ULONG Attributes;
    PSECURITY_DESCRIPTOR SecurityDescriptor;
    PSECURITY_QUALITY_OF_SERVICE SecurityQualityOfService;
} OBJECT_ATTRIBUTES, * POBJECT_ATTRIBUTES;

// --- typedef PCOBJECT_ATTRIBUTES  (phnt_ntdef.h, source: phnt)
typedef const OBJECT_ATTRIBUTES* PCOBJECT_ATTRIBUTES;

// NtCreateSection prototype  (x64 calling convention: rcx, rdx, r8, r9 then stack)
typedef NTSTATUS(NTAPI* fnNtCreateSection)(
    PHANDLE             SectionHandle,
    ACCESS_MASK         DesiredAccess,
    PCOBJECT_ATTRIBUTES ObjectAttributes,
    PLARGE_INTEGER      MaximumSize,
    ULONG               SectionPageProtection,
    ULONG               AllocationAttributes,
    HANDLE              FileHandle
);

// NtMapViewOfSection prototype  (x64 calling convention: rcx, rdx, r8, r9 then stack)
typedef NTSTATUS(NTAPI* fnNtMapViewOfSection)(
    HANDLE          SectionHandle,
    HANDLE          ProcessHandle,
    PVOID*          BaseAddress,
    ULONG_PTR       ZeroBits,
    SIZE_T          CommitSize,
    PLARGE_INTEGER  SectionOffset,
    PSIZE_T         ViewSize,
    SECTION_INHERIT InheritDisposition,
    ULONG           AllocationType,
    ULONG           PageProtection
    );

